### ISSUE TITLE
not detecting bigsur

### ISSUE THREAD

**Issue by zico225** [foroco/php-browser-detection#8]
Im running bigsur 11.3 but its detected as Catalina

Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

Also could be handy to pass full browser version number alongside decimalised version please.  Great script. Cheers

**Comment by foroco** [comment]
Hi @zico225 
I have no idea why your Chrome browser on Big Sur release sends User-Agent as on Catalina release. 
Because '15' ('minor' MacOS version number) in part of your User-Agent denotes Catalina release.

I need to make appropriate tests according to this issue.

**Comment by foroco** [comment]
I did some tests. Chromium-based browsers since version 90 on Big Sur send User-Agent as Catalina release. But differences in a revision MacOS number: 6 for Catalina and 7 for Big Sur release.
For example, '10_15_6' substring means Catalina release and '10_15_7' substring means Big Sur.
All of these detection issues fixed in the 2.4 version.
Thanks for participation.

**Comment by foroco** [comment]
Fixed in v2.4
